# Generated by Django 6.1 on 2026-08-14 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Condominium', 'Condominium'), ('Serviced Apartment', 'Serviced Apartment'), ('Apartment', 'Apartment'), ('Terrace House', 'Terrace House'), ('Landed', 'Landed'), ('Townhouse', 'Townhouse'), ('SOHO', 'SOHO')], max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_size', models.IntegerField(blank=True, null=True)),
                ('max_size', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('New Launch', 'New Launch'), ('Completed', 'Completed'), ('Sold Out', 'Sold Out')], max_length=50)),
                ('freehold', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='NearbyPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Hospital', 'Hospital'), ('School', 'School'), ('Park', 'Park'), ('Food', 'Food')], max_length=50)),
                ('distance', models.CharField(max_length=50)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_places', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=200)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='Sustainability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green_certification', models.CharField(blank=True, max_length=200)),
                ('solar_panels', models.BooleanField(default=False)),
                ('rainwater_harvesting', models.BooleanField(default=False)),
                ('recycling', models.BooleanField(default=False)),
                ('ev_charging', models.BooleanField(default=False)),
                ('green_space', models.BooleanField(default=False)),
                ('water_efficient', models.BooleanField(default=False)),
                ('motion_sensor_lighting', models.BooleanField(default=False)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sustainability', to='properties.property')),
            ],
        ),
    ]
