# Generated by Django 6.1 on 2026-08-17 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenRECertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=250)),
                ('certification_type', models.CharField(choices=[('Final Certification', 'Final Certification'), ('Provisional Certification', 'Provisional Certification'), ('Renewal 1', 'Renewal 1'), ('Renewal 2', 'Renewal 2')], max_length=50)),
                ('rating', models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=20)),
                ('developer', models.CharField(blank=True, max_length=250)),
                ('building_category', models.CharField(blank=True, max_length=150)),
                ('date_certified', models.DateField(blank=True, null=True)),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenre_certifications', to='properties.property')),
            ],
            options={
                'ordering': ['-date_certified'],
            },
        ),
    ]
